### ISSUE TITLE
Bug - Require Cycle Detected in SDK

### ISSUE THREAD

**Issue by stephanoparaskeva** [supertokens/supertokens-react-native#1]
### What Is:

Require cycle `build/index.js -> build/handleSessionExp.js -> build/index.js

<img width="381" alt="Screenshot 2020-06-13 at 10 11 29" src="https://user-images.githubusercontent.com/40718272/84565172-3f141300-ad5f-11ea-99dc-85ee7dd400b7.png">

### Steps to repro
`npm i supertokens-react-native`
``` JavaScript
import React from 'react';
import { View } from 'react-native'
import st from 'supertokens-react-native';
import { API_URL } from './config/env_options';

const App = () => {
  st.init(`${API_URL}`, 440, true, {});
  
  return (
    <View/>
  );
};

export default App;
```
`npm start`

### Versions
```    
"supertokens-react-native": "^1.0.0"
"react-native": "0.62.2",
```

**Comment by rishabhpoddar** [comment]
Please upgrade to version 1.0.1 to get the fix. If it still persists, feel free to message here :)
