### ISSUE TITLE
InteractionManager.runAfterInteractions() for releasing internal locks is risky

### ISSUE THREAD

**Issue by melvynhills** [supertokens/supertokens-react-native#106]
While investigating why all our fetch requests were not being sent after a few minutes, I realised SuperTokens locking mechanism uses [InteractionManager.runAfterInteractions()](https://github.com/supertokens/supertokens-react-native/blob/c1e0da8e645718a331bbe502dc13ce575b6e28c8/lib/ts/locking.ts#L73C13-L73C61) to release locks.

I fixed our issue by making sure our long-running looping animations use [isInteraction: false](https://reactnative.dev/docs/animated#timing).

But couldn't `requestAnimationFrame()` or `setImmediate()` be used instead? In my opinion, `InteractionManager.runAfterInteractions()` should not be used for low-level/data/core libraries unrelated to animations.

**Comment by nkshah2** [comment]
Hi @melvynhills 

Thanks for the issue, can you elaborate on why you consider `InteractionManager.runAfterInteractions()` risky?

**Comment by nkshah2** [comment]
Would you be open to raising a pull request to fix this?

**Comment by nkshah2** [comment]
Closing this since this has been reolves in 4.0.6, thanks again for the contribution!
