### ISSUE TITLE
(Intermediate) Add ability to get userId and JWT payload on the frontend

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-react-native#4]
This feature has already been implemented in `supertokens-website` repository (for reference). Specifically, you will need to:

- Implement storage, updating and deletion of the `front-token`. An example of this is [here](https://github.com/supertokens/supertokens-website/blob/master/lib/ts/index.ts#L349). The example uses cookie storage, however for RN, you should use `async-storage`

- The `getUserId` function as seen [here](https://github.com/supertokens/supertokens-website/blob/master/lib/ts/index.ts#L224).

- The `getJWTPayloadSecurely` function as seen [here](https://github.com/supertokens/supertokens-website/blob/master/lib/ts/index.ts#L232).

- Tests: Go to [this file](https://github.com/supertokens/supertokens-website/blob/master/test/axios.test.js) and search for `getJWTPayloadSecurely` and `getUserId`. Make similar changes to the react native tests..

- Finally, the above needs to be done for `axios` as well as for `fetch`.

**Comment by harshit860** [comment]
Hey Rishabh Is this issue still open.

**Comment by rishabhpoddar** [comment]
Hey @harshit860 , yes. It is. I have updated the description above to fill you in with more details, and I have assigned this issue to you.

**Comment by harshit860** [comment]
@rishabhpoddar Sure will be setting it up then.

**Comment by rishabhpoddar** [comment]
hey @harshit860 , Are you still working on this issue? I can re-assign it to you if you are :)
