### ISSUE TITLE
Implement graphql support

### ISSUE THREAD

**Issue by Kaijonsson** [supertokens/supertokens-react-native#67]
I am working on a project where we use Apollo/hasura and a nest.js backend. I want to make hasura actions for logging in. But SuperTokens interceptor doesn’t work on graph-queries/mutations etc.

**Comment by KristofferEriksson** [comment]
+1

**Comment by rishabhpoddar** [comment]
We are in the process of adding support for XHR interceptors, which I believe would enable apollo client to work with supertokens interceptors.

**Comment by Kaijonsson** [comment]
![Skärmavbild 2023-05-22 kl  16 38 44](https://github.com/supertokens/supertokens-react-native/assets/70696950/cdc567d1-ce11-436c-8f41-9266a689f8bf)

Is this issue actually fixed?

**Comment by rishabhpoddar** [comment]
For react native, we add interceptors to `fetch` automatically. Does ApolloClient use fetch or XHR?

**Comment by Kaijonsson** [comment]
I haven't really looked into it, but after i updated to latest in front end on RN, i am experiencing automatic refreshing of session at least. So i think it works. I did not get that when i was on 3.2.

**Comment by rishabhpoddar** [comment]
Sounds good. I'm closing this issue since it should work now
