### ISSUE TITLE
SignOut not invalidating Session

### ISSUE THREAD

**Issue by Kubessandra** [supertokens/supertokens-react-native#68]
After a call to `await SuperTokens.signOut()`
A call to `await SuperTokens.doesSessionExist()` still return true.

Does anyone is having the same issue ?

**Comment by rishabhpoddar** [comment]
Hey! This is related to the discord conversation here: https://discord.com/channels/603466164219281420/644849840475602944/1038823480545783809

Seems like you are explicitly setting cookieDomain on the backend to localhost whilst querying using the IP from the react native app.

Remove the cookieDomain setting on the backend and it should work.

Closing this issue for now, but feel free to reopen it
