### ISSUE TITLE
(Easy) Change a successful refresh call to be when the status code is < 300 as opposed to === 200

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-react-native#8]
In the [`onUnauthorisedResponse`](https://github.com/supertokens/supertokens-react-native/blob/ee498d75b13dcb20c7f423d7d68e90f484edce15/lib/ts/index.ts#L284) function, in [index.ts](https://github.com/supertokens/supertokens-react-native/blob/master/lib/ts/index.ts), we check if the response from the refresh API call is `=== 200`. This results in an issue where if the user instead sends something like `201`, it stops working. 

We want to change that to check if the response is `< 300`.

**Comment by arnxv0** [comment]
Can I work on this for the Hacktober Fest 2020?

**Comment by rishabhpoddar** [comment]
Hi @arnxv0. Sure! I have assigned this issue to you. Please see the updated first comment for more details on this issue.

**Comment by arnxv0** [comment]
> Hi @arnxv0. Sure! I have assigned this issue to you. Please see the updated first comment for more details on this issue.

Alright, I'll get to work soon :)

**Comment by arnxv0** [comment]
I have created a pull request, check it out and let me know :)
